[package]
name = "dbal"
version = "0.1.0"
authors = ["Alessandro Chitolina <alekitto@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
fallible-iterator = "0.2"
serde_json = "1.0"
url = "1.6"
uuid = "0.8"

[dependencies.rusqlite]
version = "0.24"
features = ["bundled", "chrono", "column_decltype", "functions", "serde_json", "uuid"]
