[package]
name = "creed"
version = "0.1.0"
authors = ["Alessandro Chitolina <alekitto@gmail.com>"]
edition = "2021"

[dependencies]
bitflags = "1"
chrono = "0.4"
crc = "3"
dashmap = "5"
delegate = "0.7"
fallible-iterator = "0.2"
futures = "0.3"
itertools = "0.10"
lazy_static = "1"
regex = "1"
serde_json = "1"
tokio = { version = "1", features = ["default", "macros", "rt"] }
url = "2"
uuid = "1"
version-compare = "0.1"

[dev-dependencies]
chrono-tz = "0.6"

[features]
default = ["mysql", "postgres", "sqlite"]
mysql = ["mysql_async"]
postgres = ["postgres-native-tls", "tokio-postgres"]
runtime-tokio-native-tls = []
runtime-tokio-rustls = []
sqlite = ["rusqlite"]

[dependencies.mysql_async]
version = "0.30"
optional = true

[dependencies.tokio-postgres]
version = "0.7.2"
optional = true

[dependencies.postgres-native-tls]
version = "0.5.0"
optional = true

[dependencies.rusqlite]
version = "0.28"
optional = true
features = ["bundled", "chrono", "column_decltype", "functions", "serde_json", "uuid"]

[dev-dependencies.tokio-test]
version = "0.4"
