name: Tests

on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      # this is cheaper than requesting the non-minimal profile
      - run: rustup component add rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [tokio]
        tls: [native-tls, rustls]
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Run cargo check
        run: cargo check --no-default-features --features sqlite,postgres,mysql,runtime-${{ matrix.runtime }}-${{ matrix.tls }}

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [tokio]
        tls: [native-tls, rustls]
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run unit tests with code coverage
        run: cargo llvm-cov --no-default-features --features runtime-${{ matrix.runtime }}-${{ matrix.tls }} --lcov --output-path lcov.info
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  sqlite:
    name: SQLite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [tokio]
    needs: check
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with code coverage
        run: cargo llvm-cov --no-default-features --features sqlite,runtime-${{ matrix.runtime }}-rustls,functional-tests --lcov --output-path lcov.info -- --test-threads=1
        env:
          DATABASE_DSN: 'sqlite://:memory:'
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  postgres:
    name: Postgres
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres: [15, 11]
        runtime: [tokio]
        tls: [native-tls, rustls]
    needs: check
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - run: |
          docker compose run -d -p 5432:5432 --name postgres_${{ matrix.postgres }} postgres_${{ matrix.postgres }}
          docker compose run -d -p 5433:5432 --name postgres_${{ matrix.postgres }}_ssl postgres_${{ matrix.postgres }}_ssl
          docker exec postgres_${{ matrix.postgres }} bash -c "until pg_isready; do sleep 1; done"

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with code coverage
        run: cargo llvm-cov --no-default-features --features postgres,runtime-${{ matrix.runtime }}-${{ matrix.tls }},functional-tests --lcov --output-path lcov.info
        env:
          DATABASE_DSN: postgres://postgres:password@localhost:5432/dbal
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Run SSL tests with code coverage
        run: cargo llvm-cov --no-default-features --features postgres,runtime-${{ matrix.runtime }}-${{ matrix.tls }},functional-tests --lcov --output-path lcov-ssl.info
        env:
          DATABASE_DSN: postgres://postgres:password@localhost:5433/dbal?ssl_mode=verify-ca&ca=.%2Ftests%2Fpostgres%2Fcerts%2Fca.crt
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info,lcov-ssl.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  mysql:
    name: MySQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql: [8, 5_6]
        runtime: [tokio]
        tls: [native-tls, rustls]
    needs: check
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - run: |
          docker compose run -d -p 3306:3306 mysql_${{ matrix.mysql }}
          docker compose run -d -p 3307:3306 mysql_${{ matrix.mysql }}_ssl
      - run: sleep 60

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with code coverage
        run: cargo llvm-cov --no-default-features --features mysql,runtime-${{ matrix.runtime }}-${{ matrix.tls }},functional-tests --lcov --output-path lcov.info
        env:
          DATABASE_DSN: mysql://root:password@localhost:3306/dbal
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Run SSL tests with code coverage
        run: cargo llvm-cov --no-default-features --features mysql,runtime-${{ matrix.runtime }}-${{ matrix.tls }},functional-tests --lcov --output-path lcov-ssl.info
        env:
          DATABASE_DSN: mysql://root:password@localhost:3307/dbal?ssl_mode=verify-ca&ca=.%2Ftests%2Fmysql%2Fcerts%2Fca.crt
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info,lcov-ssl.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mariadb: [10_6, 10_2]
        runtime: [tokio]
        tls: [native-tls, rustls]
    needs: check
    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly

      - run: docker compose run -d -p 3306:3306 mariadb_${{ matrix.mariadb }}
      - run: sleep 30

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with code coverage
        run: cargo llvm-cov --no-default-features --features mysql,runtime-${{ matrix.runtime }}-${{ matrix.tls }},functional-tests --lcov --output-path lcov.info
        env:
          DATABASE_DSN: mysql://root:password@localhost:3306/dbal
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'
          RUSTDOCFLAGS: '-Cinstrument-coverage -Ccodegen-units=1 -Cllvm-args=--inline-threshold=0 -Clink-dead-code -Coverflow-checks=off'

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
